### ISSUE TITLE
How to pack to exe?

### ISSUE THREAD

**Issue by Jak2k** [ThioJoe/Full-Stack-AI-Meme-Generator#11]
Could you include the script?

**Comment by Anish-Shobith** [comment]
@Jak2k, You can find it in Releases tab: https://github.com/ThioJoe/Full-Stack-AI-Meme-Generator/releases

**Comment by Jak2k** [comment]
> @Jak2k, You can find it in Releases tab: https://github.com/ThioJoe/Full-Stack-AI-Meme-Generator/releases

I know that. But how to pack it myself?

**Comment by ThioJoe** [comment]
Pyinstaller
