### ISSUE TITLE
Add Exe Compilation Script

### ISSUE THREAD

**Issue by ThatOneShortGuy** [ThioJoe/Full-Stack-AI-Meme-Generator#17]
Can you add your exe compilation script to the repo so we can compile it ourselves?

Depending on what you use, I may be able to help with the compilation to create more efficient releases.

**Comment by ThioJoe** [comment]
Sure, I've just added the main.spec script that can be used with pyinstaller:
https://github.com/ThioJoe/Full-Stack-AI-Meme-Generator/blob/main/main.spec
