### ISSUE TITLE
initialize_api_clients reading wrong image_platform

### ISSUE THREAD

**Issue by TomaSajt** [ThioJoe/Full-Stack-AI-Meme-Generator#5]
initialize_api_clients is trying to check whether we have stability as out image_platform, however the function isn't taking in the image_platform as a param, it's using the global image_platform variable, which is always just clipdrop.

Fix: pass in the image_platform local variable as an argument when calling this function

IMO having global variables with the same name as locals can lead to confusion.

**Comment by ThioJoe** [comment]
Ah good catch. I was planning to remove those global variables at the top of the script because I switched to using the settings file, but ran out of time before the video. I thought they weren't even being used anymore but I clearly made an oversight.

**Comment by ThioJoe** [comment]
Ok the latest release 1.0.2 should fix that, let me know if any issues continue.
